branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: study-sync
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: study-sync
  sc: git
  workspace_type: Application
